CLEANFILES=	machine @ stellar_dabtdmb.ko.debug stellar_dabtdmb.ko.symbols
KMOD=	stellar_dabtdmb
KMODDIR?=/boot/modules
FIRMWS=	stellar_dabtdmb.fw:stellar_dabtdmb.fw:3.09.02.00

.include <bsd.kmod.mk>
