CFLAGS=-I./include
SUBDIR=	firmwares
CLEANFILES=	machine @ sms1xxx.ko.debug sms1xxx.ko.symbols
SRCS=bus_if.h device_if.h usb_if.h opt_bus.h opt_usb.h \
	sms1xxx-debug.c \
	sms1xxx-endian.c \
	sms1xxx-usb.c \
	sms1xxx-firmware.c \
	sms1xxx-frontend.c \
	sms1xxx-demux.c \
	sms1xxx-ir.c \
	sms1xxx-gpio.c \
	sms1xxx.c
KMOD=sms1xxx
KMODDIR?=/boot/modules

.include <bsd.kmod.mk>
