CLEANFILES=	machine @ novab0_isdbtbda.ko.debug novab0_isdbtbda.ko.symbols x86
KMOD=	novab0_isdbtbda
KMODDIR?=/boot/modules
FIRMWS=	novab0_isdbtbda.fw:novab0_isdbtbda.fw:02.01.02.05

.include <bsd.kmod.mk>
