CLEANFILES=	machine @ novab0_isdbtbda.ko.debug novab0_isdbtbda.ko.symbols
KMOD=	novab0_isdbtbda
KMODDIR?=/boot/modules
FIRMWS=	novab0_isdbtbda.fw:novab0_isdbtbda.fw:01.03.08.01

.include <bsd.kmod.mk>
